# Inspired by https://docs.docker.com/compose/django/
version: '3.4'

services:
  db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  rabbitmq:
    image: rabbitmq:3.9-alpine
    # environment:
    #   - RABBITMQ_DEFAULT_USER=guest
    #   - RABBITMQ_DEFAULT_PASS=guest

  redis:
    image: redis

  celery:
    build: .
    environment: &app-env
      - DJANGO_SETTINGS_MODULE=nrc.conf.docker
      - SECRET_KEY=${SECRET_KEY:-\(,gc7VE(#CO<zCR3e(lRtOsw5q+U2DpG5o\X#P4PVRm*=u|E%}
      - IS_HTTPS=no
      - ALLOWED_HOSTS=*
      - CACHE_DEFAULT=redis:6379/0
      - CACHE_AXES=redis:6379/1
      - RABBITMQ_HOST=rabbitmq
      - PUBLISH_BROKER_URL=amqp://guest:guest@rabbitmq:5672/%2F
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - CELERY_LOGLEVEL=DEBUG
      - CELERY_WORKER_CONCURRENCY=${CELERY_WORKER_CONCURRENCY:-4}
      - SUBPATH=${SUBPATH:-/}
    command: /celery_worker.sh
    depends_on:
      - db
      - rabbitmq
      - redis

  celery-beat:
    build: .
    image: openzaak/open-notificaties:${TAG:-latest}
    environment: *app-env
    command: /celery_beat.sh
    depends_on:
      - db
      - rabbitmq
      - redis

  celery-flower:
    build: .
    environment: *app-env
    command: /celery_flower.sh
    ports:
      - 5555:5555
    depends_on:
      - rabbitmq

  web:
    build: .
    environment: *app-env
    ports:
      - 8000:8000
    depends_on:
      - db
      - rabbitmq
      - redis
